name: Container Scan

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-image -f backend/Dockerfile .
        continue-on-error: true

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: backend-image
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

      - name: Build frontend image
        run: docker build -t frontend-image -f frontend/Dockerfile .
        continue-on-error: true

      - name: Scan frontend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: frontend-image
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
